In [1]:
# Some basic imports
import numpy as np
import pandas as pd

import json, re, time
import logging, requests
import itertools

from pathlib import Path
from typing import Optional
from dataclasses import dataclass, asdict
from urllib.parse import urlencode, urljoin

# Useful 'constants'
REPLAY_DIR = Path('./replays/gen9-randombattle')
USER_DIR = Path('./users')

In [2]:
ratings_data = []

for item in USER_DIR.iterdir() : 
    if (item.is_file() and item.name[0]!='.') : 
        with open(item, 'r') as file: 
            user_json = json.load(file)
        try:
            rating = user_json.get('ratings',{})
            ratings_data.append(rating.get('gen9randombattle',0))
        except:
            print("Could not get `gen9randombattle` rating for %s" % item.stem)
            continue
    elif (item.name[0]=='.') : continue
    else : print("invalid file"); continue

In [3]:
len(ratings_data)

1785

In [25]:
ratings_data[0]

{'elo': 1000,
 'gxe': 45,
 'rpr': 1459.8393856609866,
 'rprd': 122.85830807679145,
 'w': 0,
 'l': 1,
 'coil': None}

In [27]:
df = pd.DataFrame(ratings_data[0], index=[0])
df

    elo  gxe          rpr        rprd  w  l  coil
0  1000   45  1459.839386  122.858308  0  1  None

In [31]:
for D in ratings_data[1:] : 
    try: 
        entry = pd.Series(D)
        df = pd.concat([df, entry.to_frame().T], ignore_index=True)
    except:
        print("Could not parse/add entry %s" % str(D))
        continue

In [38]:
df.columns

Index(['elo', 'gxe', 'rpr', 'rprd', 'w', 'l', 'coil', 0], dtype='object')

In [41]:
df.loc[ df[0] == None ]

Empty DataFrame
Columns: [elo, gxe, rpr, rprd, w, l, coil, 0]
Index: []

In [22]:
df7 = pd.DataFrame({"a": 1, "b": 2}, index=[0])
new_row = pd.Series({"a": 3, "b": 4})
pd.concat([df7, new_row.to_frame().T], ignore_index=True)

In [23]:
>>> new_row

a    3
b    4
dtype: int64

In [ ]:
>>> 
    a   b
0   1   2
1   3   4

In [18]:
df.

           elo   gxe          rpr        rprd     w     l  coil
0  1000.000000  45.0  1459.839386  122.858308     0     1  None
1  2031.957196  84.0  1812.226463   27.166525  5150  4959  None
2  1846.322596  76.3  1720.011178   27.020352   886   801  None
3  1964.806401  83.1  1800.069413   26.442412  4379  4099  None
4  1847.398726  76.3  1720.375847   26.188666  1473  1437  None

In [7]:
df.add

           elo   gxe          rpr        rprd     w     l  coil
0  1000.000000  45.0  1459.839386  122.858308     0     1  None
1  2031.957196  84.0  1812.226463   27.166525  5150  4959  None
2  1846.322596  76.3  1720.011178   27.020352   886   801  None
3  1964.806401  83.1  1800.069413   26.442412  4379  4099  None
4  1847.398726  76.3  1720.375847   26.188666  1473  1437  None

In [4]:
ratings_data[:10]

[{'elo': 1000,
  'gxe': 45,
  'rpr': 1459.8393856609866,
  'rprd': 122.85830807679145,
  'w': 0,
  'l': 1,
  'coil': None},
 {'elo': 2031.957195781082,
  'gxe': 84,
  'rpr': 1812.2264633139407,
  'rprd': 27.166524731952702,
  'w': 5150,
  'l': 4959,
  'coil': None},
 {'elo': 1846.3225963785294,
  'gxe': 76.3,
  'rpr': 1720.011178155562,
  'rprd': 27.02035217167769,
  'w': 886,
  'l': 801,
  'coil': None},
 {'elo': 1964.8064006781765,
  'gxe': 83.1,
  'rpr': 1800.0694129343376,
  'rprd': 26.442411789836125,
  'w': 4379,
  'l': 4099,
  'coil': None},
 {'elo': 1847.398725826765,
  'gxe': 76.3,
  'rpr': 1720.3758472493582,
  'rprd': 26.1886657828664,
  'w': 1473,
  'l': 1437,
  'coil': None},
 {'elo': 2015.349727791853,
  'gxe': 83.1,
  'rpr': 1800.7131068045105,
  'rprd': 25,
  'w': 871,
  'l': 827,
  'coil': None},
 {'elo': 1059.6263883170127,
  'gxe': 38.4,
  'rpr': 1408.4601799011905,
  'rprd': 87.40097582236206,
  'w': 35,
  'l': 41,
  'coil': None},
 {'elo': 2020.246390130137,
  'gxe': 86.8,
  'rpr': 1855.6022823887013,
  'rprd': 32.69519520556923,
  'w': 3537,
  'l': 3139,
  'coil': None},
 {'elo': 1843.0798472061776,
  'gxe': 79.1,
  'rpr': 1750.9744657340136,
  'rprd': 30.34651414444789,
  'w': 1100,
  'l': 1013,
  'coil': None},
 {'elo': 1999.4140375932113,
  'gxe': 82.4,
  'rpr': 1790.6843781953728,
  'rprd': 30.367663900505566,
  'w': 2958,
  'l': 2655,
  'coil': None}]